"""Run: python tests/test_parse.py

Tested against real pip-compile/pip-freeze output shapes, not just
synthetic "package==1.2.3" lines -- two real bugs (the === operator, and
extras syntax) were found exactly this way while building this module.
"""
from __future__ import annotations

import pathlib
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from lockstep.parse import parse_lockfile


class TestParseLockfile(unittest.TestCase):
    def test_simple_pin(self):
        result = parse_lockfile("requests==2.31.0\n")
        self.assertEqual(result["pinned"], {"requests": "2.31.0"})
        self.assertEqual(result["unpinned"], [])

    def test_names_are_normalized(self):
        result = parse_lockfile("Flask-Login==0.6.2\n")
        self.assertEqual(result["pinned"], {"flask-login": "0.6.2"})

    def test_blank_lines_and_comments_are_skipped(self):
        result = parse_lockfile("\n# a comment\n\nrequests==2.31.0\n")
        self.assertEqual(result["pinned"], {"requests": "2.31.0"})

    def test_inline_comment_after_a_pin(self):
        result = parse_lockfile("requests==2.31.0  # via -r requirements.in\n")
        self.assertEqual(result["pinned"], {"requests": "2.31.0"})

    def test_pip_option_lines_are_skipped(self):
        text = "-r base.txt\n--index-url https://pypi.org/simple\nrequests==2.31.0\n"
        result = parse_lockfile(text)
        self.assertEqual(result["pinned"], {"requests": "2.31.0"})

    def test_hash_pinned_continuation_lines_are_skipped(self):
        text = "requests==2.31.0 \\\n    --hash=sha256:abc123\n    --hash=sha256:def456\nclick==8.1.3\n"
        result = parse_lockfile(text)
        self.assertEqual(result["pinned"], {"requests": "2.31.0", "click": "8.1.3"})

    def test_environment_marker_is_stripped_from_the_version(self):
        result = parse_lockfile('urllib3==2.0.4 ; python_version >= "3.8"\n')
        self.assertEqual(result["pinned"], {"urllib3": "2.0.4"})

    def test_extras_syntax_does_not_break_the_pin(self):
        """requests[security]==2.31.0 -- extras are real, common syntax in
        a real pip-compile lockfile."""
        result = parse_lockfile("requests[security]==2.31.0\n")
        self.assertEqual(result["pinned"], {"requests": "2.31.0"})

    def test_arbitrary_equality_operator_is_not_mangled(self):
        """attrs===23.1.0 -- PEP 440's arbitrary-equality operator. A regex
        matching a bare '==' first would eat two of its three '=' and
        leave a leading '=' stuck on the front of the captured version --
        a real bug caught by testing this exact operator, not assumed
        equivalent to '=='."""
        result = parse_lockfile("attrs===23.1.0\n")
        self.assertEqual(result["pinned"], {"attrs": "23.1.0"})

    def test_range_specifiers_are_unpinned_not_ignored(self):
        result = parse_lockfile("click>=8.0\n")
        self.assertEqual(result["pinned"], {})
        self.assertEqual(result["unpinned"], ["click"])

    def test_bare_name_with_no_operator_is_unpinned(self):
        result = parse_lockfile("numpy\n")
        self.assertEqual(result["unpinned"], ["numpy"])

    def test_compatible_release_operator_is_unpinned(self):
        result = parse_lockfile("django~=4.2\n")
        self.assertEqual(result["unpinned"], ["django"])

    def test_empty_file_is_nothing_not_an_error(self):
        result = parse_lockfile("")
        self.assertEqual(result, {"pinned": {}, "unpinned": []})

    def test_a_realistic_mixed_file(self):
        text = (
            "# autogenerated by pip-compile\n"
            "--index-url https://pypi.org/simple\n"
            "\n"
            "requests==2.31.0\n"
            "    # via -r requirements.in\n"
            'urllib3==2.0.4 ; python_version >= "3.8"\n'
            "attrs===23.1.0\n"
            "click>=8.0\n"
            "numpy\n"
        )
        result = parse_lockfile(text)
        self.assertEqual(result["pinned"], {
            "requests": "2.31.0", "urllib3": "2.0.4", "attrs": "23.1.0",
        })
        self.assertEqual(sorted(result["unpinned"]), ["click", "numpy"])


if __name__ == "__main__":
    unittest.main()
